# Generated by Django 2.0.5 on 2018-07-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alpha_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='debtmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='customermodel',
            index=models.Index(fields=['cpf'], name='cpf_idx'),
        ),
        migrations.AddIndex(
            model_name='debtmodel',
            index=models.Index(fields=['customer'], name='customer_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
    ]
