# Generated by Django 2.0.5 on 2018-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alpha_app', '0002_auto_20180707_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
