# Generated by Django 2.0.5 on 2018-07-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_alpha_app', '0003_auto_20180707_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtmodel',
            old_name='amount',
            new_name='value',
        ),
    ]
