# Generated by Django 2.0.5 on 2018-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_delta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdossiermodel',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
